[project]
name = "assignment"
version = "0.1.0"
description = "JUA interview assignment"
readme = "README.md"
requires-python = ">=3.12,<=3.13"
authors = [
    {name = "Teo Spadotto", email = "teospadotto@gmail.com"}
]
dependencies = [
    "dask[complete]>=2024.12.1",
    "gcsfs>=2024.12.0",
    "h3>=4.1.2",
    "isort>=5.13.2",
    "mypy>=1.14.0",
    "netcdf4>=1.7.2",
    "pyarrow>=18.1.0",
    "pyspark==3.4.3",
    "pytest>=8.3.4",
    "python-snappy>=0.7.3",
    "ruff>=0.8.4",
    "xarray>=2024.11.0",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"


